InventoryManagement/Models/PurchaseOrder.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace InventoryManagement.Models
{
    public partial class PurchaseOrder : DatetimeEntity
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "Warehouse Name")]
        public int? WarehouseId { get; set; }
        [Required]
        [Display(Name = "Supplier Name")]
        public int? SupplierId { get; set; }
        [Required]
        [Display(Name = "Purchase Type")]
        public string Potype { get; set; }
        [Required]
        [Display(Name = "Contact Name")]
        public string ContactName { get; set; }
        [Required]
        [Display(Name = "Phone Number")]
        [RegularExpression(@"^([0-9]{9,11})$", ErrorMessage = "Invalid Phone Number. Please Try Again")]
        public string PhoneNumber { get; set; }
      

        public virtual Supplier Supplier { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}

InventoryManagement/Controllers/PurchaseOrderController.cs
using InventoryManagement.Data;
using InventoryManagement.Models;
using InventoryManagement.Models.ViewModel;
using InventoryManagement.PaginatedList;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InventoryManagement.Controllers
{
    public class PurchaseOrderController : Controller
    {
        private readonly InventoryManagementContext _context;

        public PurchaseOrderController(InventoryManagementContext context)
        {
            _context = context;
        }

        // GET: PurchaseOrders
        //public async Task<IActionResult> Index(string searchString)
        //{
        //    var purchaseorders = from m in _context.PurchaseOrders
        //                     select m;

        //    if (!String.IsNullOrEmpty(searchString))
        //    {
        //        purchaseorders = purchaseorders.Where(s => s.CustomerName.Contains(searchString));
        //    }

        //    return View(await purchaseorders.ToListAsync());
        //    //return View(await _context.PurchaseOrders.ToListAsync());
        //}
        public async Task<IActionResult> Index(
     string sortOrder,
     string searchString,
     int? pageNumber)
        {

            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null)
            {
                pageNumber = 1;
            }

            ViewData["CurrentFilter"] = searchString;

            var purchaseorders = from s in _context.PurchaseOrders.Include(d => d.Warehouse).Include(d => d.Supplier).AsNoTracking()
                             select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                purchaseorders = purchaseorders.Where(s => s.Supplier.SupplierName.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    purchaseorders = purchaseorders.OrderByDescending(s => s.Supplier.SupplierName);
                    break;
                case "Date":
                    purchaseorders = purchaseorders.OrderBy(s => s.CreatedDate);
                    break;
                case "date_desc":
                    purchaseorders = purchaseorders.OrderByDescending(s => s.CreatedDate);
                    break;

                default:
                    purchaseorders = purchaseorders.OrderBy(s => s.Supplier.SupplierName);
                    break;
            }

            int pageSize = 10;



            return View(await PaginatedListPurchaseOrder<PurchaseOrder>.CreateAsync(purchaseorders.AsNoTracking(), pageNumber ?? 1, pageSize));
        }


        // GET: PurchaseOrders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var purchaseorder = await _context.PurchaseOrders
                .Include(d => d.Warehouse).Include(d => d.Supplier).AsNoTracking()
                .FirstOrDefaultAsync(m => m.Id == id);
            if (purchaseorder == null)
            {
                return NotFound();
            }

            return View(purchaseorder);
        }

        // GET: PurchaseOrders/Create
        public async Task<IActionResult> Create()
        {
            var suppliers = await _context.Suppliers.OrderBy(t => t.SupplierName).ToListAsync();
            var warehouse = await _context.Warehouses.OrderBy(t => t.WarehouseName).ToListAsync();

            var purchaseOrderVM = new PurchaseOrderVM
            {
                Suppliers = new SelectList(suppliers, "Id", "SupplierName"),
                Warehouses = new SelectList(warehouse, "Id", "WarehouseName"),
            };
            return View(purchaseOrderVM);
        }

        // POST: PurchaseOrders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,WarehouseId,SupplierId,Potype,ContactName,PhoneNumber,CreatedDate,UpdatedDate,CreatedBy,UpdatedBy")] PurchaseOrder purchaseOrder)
        {
            if (ModelState.IsValid)
            {
                _context.Add(purchaseOrder);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(purchaseOrder);
        }

        // GET: PurchaseOrders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var purchaseorder = await _context.PurchaseOrders.FindAsync(id);
            if (purchaseorder == null)
            {
                return NotFound();
            }
            var suppliers = await _context.Suppliers.OrderBy(t => t.SupplierName).ToListAsync();
            var warehouse = await _context.Warehouses.OrderBy(t => t.WarehouseName).ToListAsync();

            var purchaseOrderVM = new PurchaseOrderVM
            {
                Suppliers = new SelectList(suppliers, "Id", "CustomerName"),
                Warehouses = new SelectList(warehouse, "Id", "WarehouseName"),
                PurchaseOrder = purchaseorder
            };
            return View(purchaseOrderVM);
        }

        // POST: PurchaseOrders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,WarehouseId,SupplierId,Potype,ContactName,PhoneNumber,CreatedDate,CreatedDate,UpdatedDate,CreatedBy,UpdatedBy")] PurchaseOrder purchaseOrder)
        {
            if (id != purchaseOrder.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(purchaseOrder);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!purchaseorderExists(purchaseOrder.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(purchaseOrder);
        }

        // GET: PurchaseOrders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var purchaseorder = await _context.PurchaseOrders
                .FirstOrDefaultAsync(m => m.Id == id);
            if (purchaseorder == null)
            {
                return NotFound();
            }

            return View(purchaseorder);
        }

        // POST: PurchaseOrders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var purchaseorder = await _context.PurchaseOrders.FindAsync(id);
            _context.PurchaseOrders.Remove(purchaseorder);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool purchaseorderExists(int id)
        {
            return _context.PurchaseOrders.Any(e => e.Id == id);
        }
    }
}

InventoryManagement/Views/PurchaseOrder/Create.cshtml
@model InventoryManagement.Models.ViewModel.PurchaseOrderVM

@{
    ViewData["Title"] = "Create Purchase Order";
}

<h1>Create Purchase Order</h1>

<h4>Purchase Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PurchaseOrder.SupplierId" class="control-label"></label>
                <select class="form-control" asp-for="PurchaseOrder.SupplierId" asp-items="Model.Suppliers">
                    <option value="">---- Select Customer -----</option>
                </select>
                <span asp-validation-for="PurchaseOrder.SupplierId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PurchaseOrder.WarehouseId" class="control-label"></label>
                <select class="form-control" asp-for="PurchaseOrder.WarehouseId" asp-items="Model.Warehouses">
                    <option value="">---- Select Warehouse -----</option>
                </select>
                <span asp-validation-for="PurchaseOrder.WarehouseId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PurchaseOrder.Potype" class="control-label"></label>
                <input asp-for="PurchaseOrder.Potype" class="form-control" />
                <span asp-validation-for="PurchaseOrder.Potype" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PurchaseOrder.ContactName" class="control-label"></label>
                <input asp-for="PurchaseOrder.ContactName" class="form-control" />
                <span asp-validation-for="PurchaseOrder.ContactName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PurchaseOrder.PhoneNumber" class="control-label"></label>
                <input asp-for="PurchaseOrder.PhoneNumber" class="form-control" />
                <span asp-validation-for="PurchaseOrder.PhoneNumber" class="text-danger"></span>
            </div>
            @*<div class="form-group">
            <label asp-for="CreatedDate" class="control-label"></label>
            <input asp-for="CreatedDate" class="form-control" />
            <span asp-validation-for="CreatedDate" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="UpdatedDate" class="control-label"></label>
            <input asp-for="UpdatedDate" class="form-control" />
            <span asp-validation-for="UpdatedDate" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="CreatedBy" class="control-label"></label>
            <input asp-for="CreatedBy" class="form-control" />
            <span asp-validation-for="CreatedBy" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="UpdatedBy" class="control-label"></label>
            <input asp-for="UpdatedBy" class="form-control" />
            <span asp-validation-for="UpdatedBy" class="text-danger"></span>
        </div>*@
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InventoryManagement/Views/PurchaseOrder/Delete.cshtml
@model InventoryManagement.Models.PurchaseOrder

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Purchase Order</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Supplier.SupplierName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Supplier.SupplierName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Warehouse.WarehouseName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Warehouse.WarehouseName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Potype)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Potype)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ContactName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ContactName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UpdatedBy)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

InventoryManagement/Views/PurchaseOrder/Details.cshtml
@model InventoryManagement.Models.PurchaseOrder

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Purchase Order</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Supplier.SupplierName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Supplier.SupplierName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Warehouse.WarehouseName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Warehouse.WarehouseName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Potype)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Potype)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ContactName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ContactName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UpdatedBy)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

InventoryManagement/Views/PurchaseOrder/Edit.cshtml
@model InventoryManagement.Models.ViewModel.PurchaseOrderVM

@{
    ViewData["Title"] = "Edit PurchaseOrder";
}

<h1>Edit Purchase Order</h1>

<h4>Purchase Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PurchaseOrder.Id" />
            <div class="form-group">
                <label asp-for="PurchaseOrder.SupplierId" class="control-label"></label>
                <select class="form-control" asp-for="PurchaseOrder.SupplierId" asp-items="Model.Suppliers">
                    <option value="">---- Select Customer -----</option>
                </select>
                <span asp-validation-for="PurchaseOrder.SupplierId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PurchaseOrder.WarehouseId" class="control-label"></label>
                <select class="form-control" asp-for="PurchaseOrder.WarehouseId" asp-items="Model.Warehouses">
                    <option value="">---- Select Warehouse -----</option>
                </select>
                <span asp-validation-for="PurchaseOrder.WarehouseId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PurchaseOrder.Potype" class="control-label"></label>
                <input asp-for="PurchaseOrder.Potype" class="form-control" />
                <span asp-validation-for="PurchaseOrder.Potype" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PurchaseOrder.ContactName" class="control-label"></label>
                <input asp-for="PurchaseOrder.ContactName" class="form-control" />
                <span asp-validation-for="PurchaseOrder.ContactName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PurchaseOrder.PhoneNumber" class="control-label"></label>
                <input asp-for="PurchaseOrder.PhoneNumber" class="form-control" />
                <span asp-validation-for="PurchaseOrder.PhoneNumber" class="text-danger"></span>
            </div>
            @*<div class="form-group">
            <label asp-for="CreatedDate" class="control-label"></label>
            <input asp-for="CreatedDate" class="form-control" />
            <span asp-validation-for="CreatedDate" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="UpdatedDate" class="control-label"></label>
            <input asp-for="UpdatedDate" class="form-control" />
            <span asp-validation-for="UpdatedDate" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="CreatedBy" class="control-label"></label>
            <input asp-for="CreatedBy" class="form-control" />
            <span asp-validation-for="CreatedBy" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="UpdatedBy" class="control-label"></label>
            <input asp-for="UpdatedBy" class="form-control" />
            <span asp-validation-for="UpdatedBy" class="text-danger"></span>
        </div>*@
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InventoryManagement/Views/PurchaseOrder/Index.cshtml
@model InventoryManagement.PaginatedList.PaginatedListPurchaseOrder<InventoryManagement.Models.PurchaseOrder>
@*@model InventoryManagement.Models.ProductCategoryViewModel*@

@{
    ViewData["Title"] = "PurchaseOrder Manager";
}

<h1>Purchase Order</h1>

<p>
    <a asp-action="Create">Create New</a> || 
    <a asp-area="" asp-controller="PurchaseDetail" asp-action="Index"> View Purchase Detail</a>
</p>
<form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search" asp-controller="PurchaseOrder" asp-action="Index" method="get">
    <p>
        <input type="text" name="SearchString" class="form-control bg-light" placeholder="Search for..."
               aria-label="Search" aria-describedby="basic-addon2" />
        <button class="btn btn-primary" type="submit" value="Filter">
            <i class="fas fa-search fa-sm"></i>
        </button>
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Supplier Name</a>
            </th>
            <th>
                Warehouse Name
            </th>
            <th>
                PurchaseOrder Type
            </th>
            <th>
                Contact Name
            </th>
            <th>
                Phone Number
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["DateSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Created Date</a>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Supplier.SupplierName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Warehouse.WarehouseName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Potype)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ContactName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </td>

            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled">
    Previous
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled">
    Next
</a>