InventoryManagement/Models/Supplier.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace InventoryManagement.Models
{
    public partial class Supplier : DatetimeEntity
    {
        public Supplier()
        {
            AuditLogs = new HashSet<AuditLog>();
            PurchaseOrders = new HashSet<PurchaseOrder>();
        }

        public int Id { get; set; }
        [Required]
        [Display(Name = "Supplier Name")]
        public string SupplierName { get; set; }
        [Required]
        [Display(Name = "Supplier Address")]
        public string SupplierAddress { get; set; }
        [Required]
        [Display(Name = "Customer Name")]
        public string CustomerName { get; set; }
        [Required]
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Phone Number")]
        [RegularExpression(@"^([0-9]{9,11})$", ErrorMessage = "Invalid Phone Number. Please Try Again")]
        public string PhoneNumber { get; set; }
        

        public virtual ICollection<AuditLog> AuditLogs { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
    }
}

InventoryManagement/Controllers/SupplierController.cs
using InventoryManagement.Data;
using InventoryManagement.Models;
using InventoryManagement.PaginatedList;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InventoryManagement.Controllers
{
    public class SupplierController : Controller
    {
        private readonly InventoryManagementContext _context;

        public SupplierController(InventoryManagementContext context)
        {
            _context = context;
        }

        // GET: Suppliers
        //public async Task<IActionResult> Index(string searchString)
        //{
        //    var suppliers = from m in _context.Suppliers
        //                     select m;

        //    if (!String.IsNullOrEmpty(searchString))
        //    {
        //        suppliers = suppliers.Where(s => s.SupplierName.Contains(searchString));
        //    }

        //    return View(await suppliers.ToListAsync());
        //    //return View(await _context.Suppliers.ToListAsync());
        //}
        public async Task<IActionResult> Index(
     string sortOrder,
     string searchString,
     int? pageNumber)
        {

            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null)
            {
                pageNumber = 1;
            }

            ViewData["CurrentFilter"] = searchString;

            var suppliers = from s in _context.Suppliers
                             select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                suppliers = suppliers.Where(s => s.SupplierName.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    suppliers = suppliers.OrderByDescending(s => s.SupplierName);
                    break;
                case "Date":
                    suppliers = suppliers.OrderBy(s => s.CreatedDate);
                    break;
                case "date_desc":
                    suppliers = suppliers.OrderByDescending(s => s.CreatedDate);
                    break;

                default:
                    suppliers = suppliers.OrderBy(s => s.SupplierName);
                    break;
            }

            int pageSize = 10;



            return View(await PaginatedList1<Supplier>.CreateAsync(suppliers.AsNoTracking(), pageNumber ?? 1, pageSize));
        }


        // GET: Suppliers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var unit = await _context.Suppliers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (unit == null)
            {
                return NotFound();
            }

            return View(unit);
        }

        // GET: Suppliers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Suppliers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,SupplierName,SupplierAddress,CustomerName,PhoneNumber,CreatedDate,UpdatedDate,CreatedBy,UpdatedBy")] Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                _context.Add(supplier);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(supplier);
        }

        // GET: Suppliers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var unit = await _context.Suppliers.FindAsync(id);
            if (unit == null)
            {
                return NotFound();
            }
            return View(unit);
        }

        // POST: Suppliers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,SupplierName,SupplierAddress,CustomerName,PhoneNumber,CreatedDate,UpdatedDate,CreatedBy,UpdatedBy")] Supplier supplier)
        {
            if (id != supplier.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(supplier);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!supplierExists(supplier.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(supplier);
        }

        // GET: Suppliers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var unit = await _context.Suppliers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (unit == null)
            {
                return NotFound();
            }

            return View(unit);
        }

        // POST: Suppliers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var unit = await _context.Suppliers.FindAsync(id);
            _context.Suppliers.Remove(unit);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool supplierExists(int id)
        {
            return _context.Suppliers.Any(e => e.Id == id);
        }
    }
}

InventoryManagement/Views/Supplier/Create.cshtml
@model InventoryManagement.Models.Supplier

@{
    ViewData["Title"] = "Create Supplier";
}

<h1>Create Supplier</h1>

<h4>Supplier</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SupplierName" class="control-label"></label>
                <input asp-for="SupplierName" class="form-control" />
                <span asp-validation-for="SupplierName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SupplierAddress" class="control-label"></label>
                <input asp-for="SupplierAddress" class="form-control" />
                <span asp-validation-for="SupplierAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerName" class="control-label"></label>
                <input asp-for="CustomerName" class="form-control" />
                <span asp-validation-for="CustomerName" class="text-danger"></span>
            </div>
            @*<div class="form-group">
            <label asp-for="CreatedDate" class="control-label"></label>
            <input asp-for="CreatedDate" class="form-control" />
            <span asp-validation-for="CreatedDate" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="UpdatedDate" class="control-label"></label>
            <input asp-for="UpdatedDate" class="form-control" />
            <span asp-validation-for="UpdatedDate" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="CreatedBy" class="control-label"></label>
            <input asp-for="CreatedBy" class="form-control" />
            <span asp-validation-for="CreatedBy" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="UpdatedBy" class="control-label"></label>
            <input asp-for="UpdatedBy" class="form-control" />
            <span asp-validation-for="UpdatedBy" class="text-danger"></span>
        </div>*@
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InventoryManagement/Views/Supplier/Delete.cshtml
@model InventoryManagement.Models.Supplier

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Supplier</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SupplierName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SupplierName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SupplierAddress)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SupplierAddress)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CustomerName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UpdatedBy)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

InventoryManagement/Views/Supplier/Details.cshtml
@model InventoryManagement.Models.Supplier

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Supplier</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SupplierName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SupplierName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SupplierAddress)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SupplierAddress)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CustomerName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UpdatedBy)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

InventoryManagement/Views/Supplier/Edit.cshtml
@model InventoryManagement.Models.Supplier

@{
    ViewData["Title"] = "Edit Supplier";
}

<h1>Edit Supplier</h1>

<h4>Supplier</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="SupplierName" class="control-label"></label>
                <input asp-for="SupplierName" class="form-control" />
                <span asp-validation-for="SupplierName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SupplierAddress" class="control-label"></label>
                <input asp-for="SupplierAddress" class="form-control" />
                <span asp-validation-for="SupplierAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerName" class="control-label"></label>
                <input asp-for="CustomerName" class="form-control" />
                <span asp-validation-for="CustomerName" class="text-danger"></span>
            </div>
            @*<div class="form-group">
            <label asp-for="CreatedDate" class="control-label"></label>
            <input asp-for="CreatedDate" class="form-control" />
            <span asp-validation-for="CreatedDate" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="UpdatedDate" class="control-label"></label>
            <input asp-for="UpdatedDate" class="form-control" />
            <span asp-validation-for="UpdatedDate" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="CreatedBy" class="control-label"></label>
            <input asp-for="CreatedBy" class="form-control" />
            <span asp-validation-for="CreatedBy" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="UpdatedBy" class="control-label"></label>
            <input asp-for="UpdatedBy" class="form-control" />
            <span asp-validation-for="UpdatedBy" class="text-danger"></span>
        </div>*@
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InventoryManagement/Views/Supplier/Index.cshtml
@model InventoryManagement.PaginatedList.PaginatedList1<InventoryManagement.Models.Supplier>
@*@model Inventor yManagement.Models.ProductCategoryViewModel*@

@{
    ViewData["Title"] = "Supplier Manager";
}

<h1>Supplier</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search" asp-controller="Supplier" asp-action="Index" method="get">
    <p>
        <input type="text" name="SearchString" class="form-control bg-light" placeholder="Search for..."
               aria-label="Search" aria-describedby="basic-addon2" />
        <button class="btn btn-primary" type="submit" value="Filter">
            <i class="fas fa-search fa-sm"></i>
        </button>
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Supplier Name</a>
            </th>
            <th>
                Address
            </th>
            <th>
                Phone Number
            </th>
            <th>
                Customer Name
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["DateSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Created Date</a>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.SupplierName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SupplierAddress)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CustomerName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedDate)
                </td>

                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled">
    Previous
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled">
    Next
</a>