InventoryManagement/Models/SaleOrder.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace InventoryManagement.Models
{
    public partial class SaleOrder : DatetimeEntity
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "Warehouse Name")]
        public int? WarehouseId { get; set; }
        [Required]
        [Display(Name = "Customer Name")]
        public int? CustomerId { get; set; }
        [Required]
        [Display(Name = "Sale Order Type")]
        public string Sotype { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}

InventoryManagement/Controllers/SaleOrderController.cs
using InventoryManagement.Data;
using InventoryManagement.Models;
using InventoryManagement.Models.ViewModel;
using InventoryManagement.PaginatedList;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InventoryManagement.Controllers
{
    public class SaleOrderController : Controller
    {
        private readonly InventoryManagementContext _context;

        public SaleOrderController(InventoryManagementContext context)
        {
            _context = context;
        }

        // GET: SaleOrders
        //public async Task<IActionResult> Index(string searchString)
        //{
        //    var saleorders = from m in _context.SaleOrders
        //                     select m;

        //    if (!String.IsNullOrEmpty(searchString))
        //    {
        //        saleorders = saleorders.Where(s => s.CustomerName.Contains(searchString));
        //    }

        //    return View(await saleorders.ToListAsync());
        //    //return View(await _context.SaleOrders.ToListAsync());
        //}
        public async Task<IActionResult> Index(
     string sortOrder,
     string searchString,
     int? pageNumber)
        {

            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null)
            {
                pageNumber = 1;
            }

            ViewData["CurrentFilter"] = searchString;

            var saleorders = from s in _context.SaleOrders.Include(d => d.Warehouse).Include(d => d.Customer).AsNoTracking()
                             select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                saleorders = saleorders.Where(s => s.Customer.CustomerName.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    saleorders = saleorders.OrderByDescending(s => s.Customer.CustomerName);
                    break;
                case "Date":
                    saleorders = saleorders.OrderBy(s => s.CreatedDate);
                    break;
                case "date_desc":
                    saleorders = saleorders.OrderByDescending(s => s.CreatedDate);
                    break;

                default:
                    saleorders = saleorders.OrderBy(s => s.Customer.CustomerName);
                    break;
            }

            int pageSize = 10;



            return View(await PaginatedListSaleOrder<SaleOrder>.CreateAsync(saleorders.AsNoTracking(), pageNumber ?? 1, pageSize));
        }


        // GET: SaleOrders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var unit = await _context.SaleOrders
                .Include(d => d.Warehouse).Include(d => d.Customer).AsNoTracking()
                .FirstOrDefaultAsync(m => m.Id == id);
            if (unit == null)
            {
                return NotFound();
            }

            return View(unit);
        }

        // GET: SaleOrders/Create
        public async Task<IActionResult> Create()
        {
            var customer = await _context.Customers.OrderBy(t => t.CustomerName).ToListAsync();
            var warehouse = await _context.Warehouses.OrderBy(t => t.WarehouseName).ToListAsync();

            var saleOrderVM = new SaleOrderVM
            {
                Customers = new SelectList(customer, "Id", "CustomerName"),
                Warehouses = new SelectList(warehouse, "Id", "WarehouseName"),
            };
            return View(saleOrderVM);
        }

        // POST: SaleOrders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,WarehouseId,CustomerId,Sotype,CreatedDate,UpdatedDate,CreatedBy,UpdatedBy")] SaleOrder saleOrder)
        {
            if (ModelState.IsValid)
            {
                _context.Add(saleOrder);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(saleOrder);
        }

        // GET: SaleOrders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var unit = await _context.SaleOrders.FindAsync(id);
            if (unit == null)
            {
                return NotFound();
            }
            var customer = await _context.Customers.OrderBy(t => t.CustomerName).ToListAsync();
            var warehouse = await _context.Warehouses.OrderBy(t => t.WarehouseName).ToListAsync();

            var saleOrderVM = new SaleOrderVM
            {
                Customers = new SelectList(customer, "Id", "CustomerName"),
                Warehouses = new SelectList(warehouse, "Id", "WarehouseName"),
                SaleOrder = unit
            };
            return View(saleOrderVM);
        }

        // POST: SaleOrders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,WarehouseId,CustomerId,Sotype,CreatedDate,CreatedDate,UpdatedDate,CreatedBy,UpdatedBy")] SaleOrder saleOrder)
        {
            if (id != saleOrder.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(saleOrder);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!unitExists(saleOrder.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(saleOrder);
        }

        // GET: SaleOrders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var unit = await _context.SaleOrders
                .FirstOrDefaultAsync(m => m.Id == id);
            if (unit == null)
            {
                return NotFound();
            }

            return View(unit);
        }

        // POST: SaleOrders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var unit = await _context.SaleOrders.FindAsync(id);
            _context.SaleOrders.Remove(unit);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool unitExists(int id)
        {
            return _context.SaleOrders.Any(e => e.Id == id);
        }
    }
}

InventoryManagement/Views/SaleOrder/Create.cshtml
@model InventoryManagement.Models.SaleOrderVM

@{
    ViewData["Title"] = "Create Customer";
}

<h1>Create Customer</h1>

<h4>Customer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SaleOrder.CustomerId" class="control-label"></label>
                <select class="form-control" asp-for="SaleOrder.CustomerId" asp-items="Model.Customers">
                    <option value="">---- Select Customer -----</option>
                </select>
                <span asp-validation-for="SaleOrder.CustomerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SaleOrder.WarehouseId" class="control-label"></label>
                <select class="form-control" asp-for="SaleOrder.WarehouseId" asp-items="Model.Warehouses">
                    <option value="">---- Select Warehouse -----</option>
                </select>
                <span asp-validation-for="SaleOrder.WarehouseId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SaleOrder.Sotype" class="control-label"></label>
                <input asp-for="SaleOrder.Sotype" class="form-control" />
                <span asp-validation-for="SaleOrder.Sotype" class="text-danger"></span>
            </div>
            @*<div class="form-group">
            <label asp-for="CreatedDate" class="control-label"></label>
            <input asp-for="CreatedDate" class="form-control" />
            <span asp-validation-for="CreatedDate" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="UpdatedDate" class="control-label"></label>
            <input asp-for="UpdatedDate" class="form-control" />
            <span asp-validation-for="UpdatedDate" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="CreatedBy" class="control-label"></label>
            <input asp-for="CreatedBy" class="form-control" />
            <span asp-validation-for="CreatedBy" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="UpdatedBy" class="control-label"></label>
            <input asp-for="UpdatedBy" class="form-control" />
            <span asp-validation-for="UpdatedBy" class="text-danger"></span>
        </div>*@
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InventoryManagement/Views/SaleOrder/Delete.cshtml
@model InventoryManagement.Models.SaleOrder

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Customer</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Customer.CustomerName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Customer.CustomerName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Warehouse.WarehouseName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Warehouse.WarehouseName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Sotype)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Sotype)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UpdatedBy)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

InventoryManagement/Views/SaleOrder/Details.cshtml
@model InventoryManagement.Models.SaleOrder

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>
@*<a asp-area="" asp-route-id="@Model.Id" asp-controller="SaleOrderDetail" asp-action="Create">Create Sale Order Detail</a>*@
<div>
    <h4>Sale Order</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Customer.CustomerName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Customer.CustomerName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Warehouse.WarehouseName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Warehouse.WarehouseName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Sotype)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Sotype)
        </dd>
        @*<dt class="col-sm-2">
            Sale Order Detail
        </dt>
        <dd class="col-sm-10">
            <a asp-route-id="@Model.Id" asp-area="" asp-controller="SaleOrderDetail" asp-action="Detail">Click To View</a>
        </dd>*@
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UpdatedBy)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

InventoryManagement/Views/SaleOrder/Edit.cshtml
@model InventoryManagement.Models.ViewModel.SaleOrderVM

@{
    ViewData["Title"] = "Edit SaleOrder";
}

<h1>Edit SaleOrder</h1>

<h4>SaleOrder</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="SaleOrder.Id" />
            <div class="form-group">
                <label asp-for="SaleOrder.CustomerId" class="control-label"></label>
                <select class="form-control" asp-for="SaleOrder.CustomerId" asp-items="Model.Customers">
                    <option value="">---- Select Customer -----</option>
                </select>
                <span asp-validation-for="SaleOrder.CustomerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SaleOrder.WarehouseId" class="control-label"></label>
                <select class="form-control" asp-for="SaleOrder.WarehouseId" asp-items="Model.Warehouses">
                    <option value="">---- Select Warehouse -----</option>
                </select>
                <span asp-validation-for="SaleOrder.WarehouseId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SaleOrder.Sotype" class="control-label"></label>
                <input asp-for="SaleOrder.Sotype" class="form-control" />
                <span asp-validation-for="SaleOrder.Sotype" class="text-danger"></span>
            </div>
            @*<div class="form-group">
            <label asp-for="CreatedDate" class="control-label"></label>
            <input asp-for="CreatedDate" class="form-control" />
            <span asp-validation-for="CreatedDate" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="UpdatedDate" class="control-label"></label>
            <input asp-for="UpdatedDate" class="form-control" />
            <span asp-validation-for="UpdatedDate" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="CreatedBy" class="control-label"></label>
            <input asp-for="CreatedBy" class="form-control" />
            <span asp-validation-for="CreatedBy" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="UpdatedBy" class="control-label"></label>
            <input asp-for="UpdatedBy" class="form-control" />
            <span asp-validation-for="UpdatedBy" class="text-danger"></span>
        </div>*@
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InventoryManagement/Views/SaleOrder/Index.cshtml
@model InventoryManagement.PaginatedList.PaginatedListSaleOrder<InventoryManagement.Models.SaleOrder>
@*@model InventoryManagement.Models.ProductCategoryViewModel*@

@{
    ViewData["Title"] = "SaleOrder Manager";
}

<h1>Sale Order</h1>

<p>
    <a asp-action="Create">Create New </a> ||
    <a asp-area="" asp-controller="SaleOrderDetail" asp-action="Index"> View Sale Order Detail</a>
</p>
<form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search" asp-controller="SaleOrder" asp-action="Index" method="get">
    <p>
        <input type="text" name="SearchString" class="form-control bg-light" placeholder="Search for..."
               aria-label="Search" aria-describedby="basic-addon2" />
        <button class="btn btn-primary" type="submit" value="Filter">
            <i class="fas fa-search fa-sm"></i>
        </button>
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Customer Name</a>
            </th>
            <th>
               Warehouse Name
            </th>
            <th>
                SaleOrder Type
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["DateSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Created Date</a>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Customer.CustomerName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Warehouse.WarehouseName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Sotype)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedDate)
                </td>

                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled">
    Previous
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled">
    Next
</a>